services:
  clone-xs:  # service name must be lowercase
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
    volumes:
      - ./config:/app/config
