import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'guide/quickstart',
        'guide/use-cases',
        'guide/setup',
        'guide/authentication',
        'guide/architecture',
        'guide/web-ui',
      ],
    },
    {
      type: 'category',
      label: 'Overview',
      collapsed: true,
      items: [
        'guide/audit',
        'guide/metrics',
        'guide/reports',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [
        'guide/clone',
        'guide/advanced-clone',
        'guide/convert',
        'guide/diff-and-compare',
        'guide/sync',
        'guide/continuous-sync',
        'guide/rollback',
        'guide/snapshots',
        'guide/demo-data',
        'guide/dlt',
        'guide/advanced-tables',
      ],
    },
    {
      type: 'category',
      label: 'Discovery',
      collapsed: true,
      items: [
        'guide/explore',
        'guide/data-lab',
        'guide/ai-assistant',
        'guide/notebooks',
        'guide/lineage',
        'guide/view-deps',
        'guide/impact',
      ],
    },
    {
      type: 'category',
      label: 'Platforms',
      collapsed: true,
      items: [
        'guide/marketplace',
        'guide/environments',
        'guide/databricks-app',
        'guide/desktop',
      ],
    },
    {
      type: 'category',
      label: 'Management',
      collapsed: true,
      items: [
        'guide/monitoring',
        'guide/observability',
        'guide/storage-metrics',
        'guide/analytics',
        'guide/config',
      ],
    },
    {
      type: 'category',
      label: 'Governance Portal',
      collapsed: true,
      items: [
        'guide/governance',
        'guide/glossary',
        'guide/search',
        'guide/certifications',
        'guide/contracts',
        'guide/sla',
        'guide/change-history',
        'guide/rbac',
        'guide/nl-rules',
        'guide/data-products',
        'guide/rtbf',
        'guide/dsar',
      ],
    },
    {
      type: 'category',
      label: 'Security & Compliance',
      collapsed: true,
      items: [
        'guide/pii-detection',
        'guide/compliance-frameworks',
        'guide/validation',
        'guide/safety',
      ],
    },
    {
      type: 'category',
      label: 'Data Quality Portal',
      collapsed: true,
      items: [
        'guide/data-quality',
        'guide/dq-suite',
        'guide/dq-freshness',
        'guide/dq-volume',
        'guide/dq-anomalies',
        'guide/dq-incidents',
        'guide/dqx',
        'guide/dq-rules',
        'guide/dq-results',
        'guide/dq-scorecard',
        'guide/expectations',
        'guide/reconciliation',
        'guide/profiling',
        'guide/schema-drift',
        'guide/dq-trust-scores',
        'guide/dq-coverage',
        'guide/dq-correlations',
        'guide/dq-observability',
        'guide/dq-automation',
        'guide/dq-discovery',
      ],
    },
    {
      type: 'category',
      label: 'FinOps Portal',
      collapsed: true,
      items: [
        'guide/finops',
        'guide/finops-billing',
        'guide/finops-storage',
        'guide/finops-compute',
        'guide/finops-breakdown',
        'guide/finops-query-costs',
        'guide/finops-job-costs',
        'guide/finops-recommendations',
        'guide/finops-warehouses',
        'guide/finops-storage-optimization',
        'guide/finops-budgets',
        'guide/finops-trends',
        'guide/finops-copq',
        'guide/cost-estimator',
      ],
    },
    {
      type: 'category',
      label: 'Automation Portal',
      collapsed: true,
      items: [
        'guide/automation',
        'guide/pipelines',
        'guide/templates',
        'guide/playbooks',
        'guide/scheduling',
        'guide/create-job',
        'guide/plugins',
        'guide/cicd',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure Portal',
      collapsed: true,
      items: [
        'guide/warehouse',
        'guide/lakehouse-monitor',
        'guide/federation',
        'guide/delta-sharing',
      ],
    },
    {
      type: 'category',
      label: 'Master Data Management',
      collapsed: true,
      items: [
        'guide/mdm',
        'guide/golden-records',
        'guide/match-merge',
        'guide/relationships',
        'guide/merge-history',
        'guide/stewardship',
        'guide/hierarchies',
        'guide/mdm-templates',
        'guide/reference-data',
        'guide/negative-match',
        'guide/mdm-settings',
        'guide/mdm-scorecards',
        'guide/mdm-profiling',
        'guide/cross-domain',
        'guide/consent',
        'guide/mdm-audit-log',
        'guide/mdm-reports',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [
        'guide/advanced-features',
        'guide/ml-assets',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/cli',
        'reference/api',
        'reference/configuration',
        'reference/faq',
        'reference/release-validation',
        'reference/changelog',
      ],
    },
  ],
};

export default sidebars;
