"""Continuous sync — PREVIEW ONLY in v0.11.0.

Generates a Structured Streaming job specification that would keep a
destination catalog ≤ N seconds behind source using Change Data Feed. The
actual submission + lifecycle management (start, stop, lag monitoring,
checkpoint recovery) is **not implemented in v0.11.0** — this module
produces the plan, a future release will wire it to ``client.jobs.submit()``.

Why scaffold? CDF streaming needs a long-running job infrastructure that
Clone-Xs doesn't have today — existing jobs are "submit and complete". A
dedicated service lifecycle + UI for stream health deserves its own release.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def build_streaming_plan(
    *,
    source_catalog: str,
    destination_catalog: str,
    tables: list[str] | None = None,
    schema: str | None = None,
    trigger_ms: int = 30_000,
    checkpoint_root: str | None = None,
) -> dict[str, Any]:
    """Build a declarative plan for a continuous-sync Structured Streaming job.

    The plan is valid input for Databricks Jobs API (``jobs.submit`` with a
    ``spark_python_task``) once a runtime submits it. For now it's rendered
    in the UI + downloadable as JSON.

    Args:
        source_catalog / destination_catalog: UC catalog names
        tables: optional list of ``schema.table`` FQNs. If omitted, plan
            applies to every table in the given ``schema`` that has
            ``delta.enableChangeDataFeed=true``.
        schema: shortcut when tables is None — "all tables in this schema"
        trigger_ms: min time between microbatches
        checkpoint_root: DBFS / Volume path where each table's checkpoint
            lives. Required for production; defaults to a placeholder.

    Returns:
        Plan dict — runnable by a future scheduler, downloadable as JSON today.
    """
    if not tables and not schema:
        raise ValueError("Either `tables` (explicit list) or `schema` (all in schema) is required")

    checkpoint_root = checkpoint_root or f"/Volumes/{destination_catalog}/_sys/continuous_sync"
    py_code = _stream_template(source_catalog, destination_catalog, trigger_ms, checkpoint_root)

    plan = {
        "version": 1,
        "status": "preview_only",
        "note": (
            "Continuous sync is preview-only in v0.11.0. The plan below is a "
            "valid Databricks Jobs spec but Clone-Xs does not submit it yet. "
            "Copy it to your scheduler, or wait for the v0.12.0 execution engine."
        ),
        "source_catalog": source_catalog,
        "destination_catalog": destination_catalog,
        "target": {"schema": schema, "tables": tables or []},
        "trigger_ms": trigger_ms,
        "checkpoint_root": checkpoint_root,
        "prerequisites": [
            "Change Data Feed enabled on every source table in scope "
            "(ALTER TABLE … SET TBLPROPERTIES (delta.enableChangeDataFeed = true))",
            "Primary key declared on each destination table (for MERGE join)",
            "Write permissions on checkpoint_root",
        ],
        "job_spec": {
            "run_name": f"clone-xs-continuous-sync-{destination_catalog}",
            "tasks": [
                {
                    "task_key": "continuous_sync",
                    "spark_python_task": {"python_file": "<inlined_below>"},
                    "new_cluster": None,  # caller fills in — serverless or shared
                }
            ],
            "inline_python": py_code,
        },
    }
    return plan


def _stream_template(
    source_catalog: str, dest_catalog: str, trigger_ms: int, checkpoint_root: str
) -> str:
    """The Python body the submitted streaming job would run."""
    return f"""
# Auto-generated by Clone-Xs build_streaming_plan() — PREVIEW ONLY in v0.11.0.
# Runs one readStream→writeStream per table in scope. Each table needs a PK.
from pyspark.sql.functions import col
import json, sys

SOURCE_CATALOG = {source_catalog!r}
DEST_CATALOG = {dest_catalog!r}
TRIGGER_MS = {trigger_ms}
CHECKPOINT_ROOT = {checkpoint_root!r}

# Caller injects the list at runtime via dbutils widget or env var:
tables = [t.strip() for t in (dbutils.widgets.get('tables') or '').split(',') if t.strip()]
assert tables, "No tables in scope"

for fqn in tables:
    schema, table = fqn.split('.', 1)
    src = f"{{SOURCE_CATALOG}}.{{schema}}.{{table}}"
    dst = f"{{DEST_CATALOG}}.{{schema}}.{{table}}"
    cp = f"{{CHECKPOINT_ROOT}}/{{schema}}/{{table}}"

    reader = (spark.readStream
      .format("delta")
      .option("readChangeFeed", "true")
      .table(src))

    # NOTE: production code needs a forEachBatch MERGE with the table's primary
    # key. This placeholder does an append-only write so the Jobs runtime can
    # validate the plan. The v0.12.0 execution engine will replace this.
    query = (reader.writeStream
      .format("delta")
      .option("checkpointLocation", cp)
      .trigger(processingTime=f"{{TRIGGER_MS}} milliseconds")
      .toTable(dst))
""".strip()
