"""Synthetic media generators for the /demo-data Media tab.

Pairs with `src.demo_documents` — same registry / orchestrator /
destination-radio pattern, different output shapes:

  - **Images** (PNG): synthesised in Pillow from gradients + noise +
    geometric primitives. No bundled assets — everything is generated
    from scratch so the repo doesn't carry license-bound binary blobs.
  - **Audio** (WAV): synthesised via stdlib `wave` (sine waves at
    voice frequencies + white noise). Operator gets a Faker-generated
    transcript as the file's "voicemail message" text in the metadata.
  - **Video** (MP4): generated by shelling out to ffmpeg's `lavfi`
    test-pattern source (no input files needed). When ffmpeg isn't on
    PATH, the type fails cleanly with an install hint while every
    other type continues.

Why pure synthesis instead of bundled assets:

  - The repo doesn't have to track / license / re-distribute binary
    blobs (audio clips, photos, X-ray samples).
  - The synthesis is fast (~5 ms per image, ~50 ms per WAV, ~500 ms
    per MP4 clip) and produces files that are clearly demo-shaped.
  - Operators get reproducible output by passing `faker_seed`.

Architecture is identical to demo_documents:

    DOCUMENT_TYPES → MEDIA_TYPES (same shape)
    is_available() probes Pillow at module-import time
    generate_media() is the orchestrator with the same destination radio
"""

from __future__ import annotations

import io
import json
import logging
import math
import random
import shutil
import struct
import subprocess
import tempfile
import uuid
import wave
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from databricks.sdk import WorkspaceClient

from src.client import execute_sql

logger = logging.getLogger(__name__)


# ── Lazy import probe ──────────────────────────────────────────────
#
# Mirrors `src.demo_documents.is_available()` — the router gates on
# this before dispatch and surfaces a clean 503 with an install hint
# when the [media] extra isn't installed.

MEDIA_AVAILABLE: bool = False
_UNAVAILABLE_REASON: str | None = (
    "The `[media]` optional extra is not installed. Run "
    "`pip install clone-xs[media]` (which pulls Pillow) and restart "
    "the API server. The video_clip type also requires the `ffmpeg` "
    "system binary on PATH — install with Homebrew (`brew install "
    "ffmpeg`) or apt (`apt-get install ffmpeg`)."
)
try:
    import importlib.util as _ilutil

    if _ilutil.find_spec("PIL") is not None:
        MEDIA_AVAILABLE = True
        _UNAVAILABLE_REASON = None
except Exception as _e:  # pragma: no cover — defensive
    _UNAVAILABLE_REASON = f"media deps probe failed: {_e}"


def is_available() -> tuple[bool, str | None]:
    """Return ``(available, reason)``. The router uses this to render
    a calm install-hint banner when Pillow is missing."""
    return MEDIA_AVAILABLE, _UNAVAILABLE_REASON


def _ffmpeg_available() -> tuple[bool, str | None]:
    """Per-tick probe for ffmpeg. Distinct from Pillow because ffmpeg
    is a system binary that may be missing even when Pillow is
    installed. The video_clip generator uses this to fail cleanly
    without aborting other types."""
    if shutil.which("ffmpeg"):
        return True, None
    return False, (
        "`ffmpeg` is not on PATH — required for the video_clip media "
        "type only. Install with `brew install ffmpeg` (macOS) or "
        "`apt-get install ffmpeg` (Linux). Other media types work "
        "without it."
    )


# ── Media-type → generator registry ────────────────────────────────

MEDIA_TYPES: dict[str, dict[str, str]] = {
    "img_xray": {
        "category": "Image",
        "label": "Synthetic X-ray (PNG)",
        "extension": "png",
        "gen_fn": "_gen_img_xray",
    },
    "img_scan": {
        "category": "Image",
        "label": "Scanned page (PNG)",
        "extension": "png",
        "gen_fn": "_gen_img_scan",
    },
    "img_photo": {
        "category": "Image",
        "label": "Generic photo (PNG)",
        "extension": "png",
        "gen_fn": "_gen_img_photo",
    },
    "audio_voicemail": {
        "category": "Audio",
        "label": "Voicemail clip (WAV)",
        "extension": "wav",
        "gen_fn": "_gen_audio_voicemail",
    },
    "video_clip": {
        "category": "Video",
        "label": "Short MP4 clip (ffmpeg)",
        "extension": "mp4",
        "gen_fn": "_gen_video_clip",
    },
}


# Empirical averages calibrated by running each generator against the
# `_AVG_BYTES_FIXTURE` corpus on a developer machine. Used by the
# preview endpoint — operators see "approximately N MB total" before
# they click Generate.
_AVG_BYTES_PER_TYPE: dict[str, int] = {
    "img_xray": 85_000,  # 512x512 PNG with gradient + noise
    "img_scan": 42_000,  # 800x1000 PNG, mostly text
    "img_photo": 65_000,  # 600x400 PNG with gradients
    "audio_voicemail": 88_000,  # 2 sec WAV @ 22050 Hz mono
    "video_clip": 120_000,  # 3 sec MP4 H.264 320x240
}

_GEN_PER_SECOND_PER_TYPE: dict[str, int] = {
    "img_xray": 200,
    "img_scan": 150,
    "img_photo": 250,
    "audio_voicemail": 100,  # synthesis + WAV header writing
    "video_clip": 2,  # ffmpeg subprocess dominates
}


# ── Image generators (Pillow) ─────────────────────────────────────


def _gen_img_xray(industry: str, fkr: Any, ai_client: Any | None) -> tuple[bytes, dict]:
    """Synthesise a 512x512 grayscale PNG that reads as "X-ray-shaped".

    Composition: dark background, brighter radial gradient at the
    centre (mimicking the brighter bony anatomy in a real chest X-ray),
    plus a small amount of high-frequency noise so the image isn't a
    perfect mathematical shape. No real medical imaging is used.
    """
    from PIL import Image, ImageDraw, ImageFilter

    size = 512
    img = Image.new("L", (size, size), color=8)  # near-black background
    draw = ImageDraw.Draw(img)

    # Radial gradient — concentric rings of decreasing brightness
    # toward the edge. This is the "torso shape" under a chest X-ray.
    cx, cy = size // 2, size // 2
    for r in range(size // 2, 0, -2):
        # Brightness 50 at edge, 230 at centre — high but not blown out.
        brightness = int(230 - 180 * (r / (size / 2)) ** 1.4)
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=brightness)

    # Add a couple of brighter "bone" outlines (vertical spine, ribs)
    # to make the image read as anatomical rather than a pure gradient.
    spine_w = random.randint(14, 22)
    draw.rectangle(
        [cx - spine_w // 2, cy - 180, cx + spine_w // 2, cy + 180],
        fill=210,
    )
    for rib_y in range(cy - 140, cy + 140, 30):
        rib_offset = random.randint(8, 14)
        draw.arc(
            [cx - 180, rib_y - rib_offset, cx + 180, rib_y + rib_offset],
            start=20,
            end=160,
            fill=180,
            width=4,
        )

    # Soft blur so the synthetic edges don't look like clipart.
    img = img.filter(ImageFilter.GaussianBlur(radius=2))

    # Add fine-grained noise. Pillow's `eval` per-pixel is slow but
    # 512×512 finishes in ~30ms which is fine for demo throughput.
    noise = Image.effect_noise((size, size), 12)
    img = Image.blend(img, noise.convert("L"), 0.08)

    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)

    case_id = f"XR-{uuid.uuid4().hex[:10].upper()}"
    return buf.getvalue(), {
        "case_id": case_id,
        "modality": "X-ray",
        "view": random.choice(["AP chest", "PA chest", "Lateral chest"]),
        "patient_age_years": random.randint(18, 88),
        "dimensions": f"{size}x{size}",
        "format": "PNG (synthetic — not a real X-ray)",
    }


def _gen_img_scan(industry: str, fkr: Any, ai_client: Any | None) -> tuple[bytes, dict]:
    """Synthesise a "scanned document page" PNG.

    Composition: off-white paper background with a subtle texture
    (simulates scanner noise), a centred document title, a few
    paragraphs of placeholder text, and a tiny rotation/skew to
    look like a real scan rather than a digital export.
    """
    from PIL import Image, ImageDraw, ImageFont

    width, height = 800, 1000
    # Off-white paper colour, very slight blue cast — same shade real
    # scanners produce.
    bg = (250, 249, 245)
    img = Image.new("RGB", (width, height), color=bg)
    draw = ImageDraw.Draw(img)

    # Try the system default font; fall back to PIL's bitmap font if
    # the system one isn't available (CI runners often lack TTFs).
    try:
        title_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 28)
        body_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 14)
    except Exception:
        title_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    # Title — centred near the top.
    title = fkr.catch_phrase().title()
    draw.text((width // 2 - 200, 80), title, fill=(20, 20, 20), font=title_font)
    draw.text(
        (width // 2 - 100, 120),
        f"Document #{fkr.bothify('??-####')} · {datetime.now().strftime('%B %d, %Y')}",
        fill=(80, 80, 80),
        font=body_font,
    )

    # 6 paragraphs of placeholder body text.
    y = 170
    paragraphs = []
    for _ in range(6):
        text = fkr.text(max_nb_chars=350)
        # Word-wrap at ~80 chars; the bitmap font isn't great for
        # measurement so this approximates rather than measures.
        words = text.split()
        line = ""
        for w in words:
            if len(line) + len(w) + 1 > 80:
                draw.text((60, y), line, fill=(30, 30, 30), font=body_font)
                y += 18
                line = w
            else:
                line = (line + " " + w).strip()
        if line:
            draw.text((60, y), line, fill=(30, 30, 30), font=body_font)
            y += 18
        y += 12  # paragraph spacing
        paragraphs.append(text[:80])

    # Subtle rotation so it looks scanned, not exported.
    angle = random.uniform(-0.6, 0.6)
    if abs(angle) > 0.05:
        img = img.rotate(angle, fillcolor=bg, resample=Image.BILINEAR)

    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue(), {
        "title": title,
        "page_dimensions": f"{width}x{height}",
        "paragraph_count": len(paragraphs),
        "format": "PNG (synthetic scanned page)",
    }


def _gen_img_photo(industry: str, fkr: Any, ai_client: Any | None) -> tuple[bytes, dict]:
    """Synthesise a generic 600x400 photo-shaped PNG.

    Composition: random gradient background + 3-7 abstract geometric
    shapes (circles, rectangles, polygons) in saturated colors. Looks
    distinctly demo-shaped — not trying to fool anyone into thinking
    it's a real photo, just provides bytes that exercise the image-
    handling pipeline.
    """
    from PIL import Image, ImageDraw

    width, height = 600, 400
    # Random gradient — pick two random colours and interpolate.
    c1 = (random.randint(40, 200), random.randint(40, 200), random.randint(40, 200))
    c2 = (random.randint(40, 200), random.randint(40, 200), random.randint(40, 200))
    img = Image.new("RGB", (width, height), color=c1)
    pixels = img.load()
    for y in range(height):
        t = y / height
        r = int(c1[0] * (1 - t) + c2[0] * t)
        g = int(c1[1] * (1 - t) + c2[1] * t)
        b = int(c1[2] * (1 - t) + c2[2] * t)
        for x in range(width):
            pixels[x, y] = (r, g, b)

    # Random shapes on top.
    draw = ImageDraw.Draw(img)
    shape_count = random.randint(3, 7)
    for _ in range(shape_count):
        shape = random.choice(["ellipse", "rectangle", "polygon"])
        color = (
            random.randint(0, 255),
            random.randint(0, 255),
            random.randint(0, 255),
        )
        x1, y1 = random.randint(0, width - 50), random.randint(0, height - 50)
        x2, y2 = x1 + random.randint(30, 200), y1 + random.randint(30, 200)
        if shape == "ellipse":
            draw.ellipse([x1, y1, x2, y2], fill=color)
        elif shape == "rectangle":
            draw.rectangle([x1, y1, x2, y2], fill=color)
        else:
            # Triangle
            draw.polygon([(x1, y2), ((x1 + x2) // 2, y1), (x2, y2)], fill=color)

    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue(), {
        "dimensions": f"{width}x{height}",
        "shape_count": shape_count,
        "format": "PNG (synthetic abstract)",
    }


# ── Audio generator (stdlib wave) ─────────────────────────────────


def _gen_audio_voicemail(industry: str, fkr: Any, ai_client: Any | None) -> tuple[bytes, dict]:
    """Synthesise a 2-second WAV voicemail-shaped clip via stdlib `wave`.

    Audio: a sine wave at 220 Hz (low-male-voice fundamental) modulated
    by a slowly-varying envelope to suggest speech cadence. Single
    channel, 22050 Hz sample rate, 16-bit PCM. ~88 KB per file.

    The metadata carries a Faker-generated transcript — what the
    voicemail "would have said" — so RAG / NLP demos that pair
    audio bytes with text have something interesting to embed.
    """
    sample_rate = 22050
    duration_s = 2.0
    n_samples = int(sample_rate * duration_s)

    # Caller / callee context for the metadata.
    caller_name = fkr.name()
    caller_phone = fkr.phone_number()
    callee_name = fkr.name()

    # Faker-drafted "transcript" — what the audio would say. Pure
    # text, lives in the metadata and gets surfaced as a `.txt`
    # sidecar by the orchestrator if `_with_transcript_sidecar` is
    # set (v2 — for now it's just metadata).
    transcript = (
        f"Hi {callee_name.split()[0]}, this is {caller_name.split()[0]}. "
        f"I'm calling about {fkr.bs()}. Could you give me a call back at "
        f"{caller_phone} when you have a moment? Thanks."
    )

    # Synthesise audio. Sine wave + amplitude envelope that varies on a
    # ~0.4 second cycle to suggest speech rhythm. NOT actual TTS —
    # just bytes that exercise the audio-handling pipeline.
    samples = []
    for i in range(n_samples):
        t = i / sample_rate
        carrier = math.sin(2 * math.pi * 220 * t)
        envelope = 0.5 + 0.5 * math.sin(2 * math.pi * 2.5 * t)
        amp = int(carrier * envelope * 16000)  # 16-bit signed range
        samples.append(amp)

    # Pack into a WAV file via stdlib `wave`.
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)  # mono
        wf.setsampwidth(2)  # 16-bit
        wf.setframerate(sample_rate)
        # struct.pack is the Pythonic way to write multiple int16
        # frames in one shot — much faster than a per-frame call.
        wf.writeframes(struct.pack(f"<{n_samples}h", *samples))

    return buf.getvalue(), {
        "caller_name": caller_name,
        "caller_phone": caller_phone,
        "callee_name": callee_name,
        "transcript": transcript,
        "duration_ms": int(duration_s * 1000),
        "sample_rate_hz": sample_rate,
        "format": "WAV (synthetic 220Hz sine, mono, 16-bit)",
    }


# ── Video generator (ffmpeg subprocess) ───────────────────────────


def _gen_video_clip(industry: str, fkr: Any, ai_client: Any | None) -> tuple[bytes, dict]:
    """Synthesise a 3-second MP4 clip by shelling out to ffmpeg.

    Uses ffmpeg's `lavfi` source to generate a test-pattern video
    (no input files needed) plus a sine-wave audio track. The whole
    thing assembles in a single ffmpeg call:

      ffmpeg -f lavfi -i testsrc=... -f lavfi -i sine=... \\
             -shortest -pix_fmt yuv420p -c:v libx264 -preset ultrafast \\
             -c:a aac output.mp4

    Output: ~120 KB MP4 with H.264 video + AAC audio. Plays in any
    standard video player.

    Raises ``RuntimeError`` if ffmpeg isn't on PATH so the
    orchestrator can record this as a per-cell failure with a clear
    install hint, without aborting other media types.
    """
    available, reason = _ffmpeg_available()
    if not available:
        raise RuntimeError(reason or "ffmpeg not available")

    duration_s = 3
    width, height = 320, 240
    fps = 15
    audio_freq_hz = random.choice([440, 880, 660, 523])

    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as out:
        out_path = out.name
    try:
        cmd = [
            "ffmpeg",
            "-y",  # overwrite output
            "-f",
            "lavfi",
            "-i",
            f"testsrc=duration={duration_s}:size={width}x{height}:rate={fps}",
            "-f",
            "lavfi",
            "-i",
            f"sine=frequency={audio_freq_hz}:duration={duration_s}",
            "-shortest",  # stop at shortest stream
            "-pix_fmt",
            "yuv420p",  # broad-compat pixel format
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",  # speed > size for demo bytes
            "-c:a",
            "aac",
            "-b:a",
            "64k",
            "-loglevel",
            "error",  # ffmpeg is too chatty otherwise
            out_path,
        ]
        result = subprocess.run(
            cmd,
            capture_output=True,
            timeout=30,
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"ffmpeg failed (exit {result.returncode}): "
                f"{result.stderr.decode('utf-8', errors='replace')[:300]}"
            )
        video_bytes = Path(out_path).read_bytes()
    finally:
        Path(out_path).unlink(missing_ok=True)

    return video_bytes, {
        "duration_ms": duration_s * 1000,
        "dimensions": f"{width}x{height}",
        "fps": fps,
        "audio_frequency_hz": audio_freq_hz,
        "codec": "h264 + aac",
        "format": "MP4 (ffmpeg testsrc + sine)",
    }


# ── Top-level orchestrator ────────────────────────────────────────


def _ensure_volume(client: WorkspaceClient, warehouse_id: str, vol_fqn: str) -> None:
    """Mirrors the Documents tab's auto-create. Idempotent."""
    execute_sql(client, warehouse_id, f"CREATE VOLUME IF NOT EXISTS {vol_fqn}")


def _ensure_catalog_table(
    client: WorkspaceClient,
    warehouse_id: str,
    fqn: str,
    *,
    direct: bool,
) -> None:
    """Create-or-replace the catalog/direct table for media.

    Schema mirrors `demo_documents` but the per-media-type metadata
    is media-shaped (duration_ms, dimensions, codec) rather than
    document-shaped (page_count). Both layouts share the
    `metadata_json` column for the per-type extras.
    """
    if direct:
        sql = f"""
        CREATE OR REPLACE TABLE {fqn} (
            file_id          STRING,
            media_type       STRING,
            file_extension   STRING,
            size_bytes       BIGINT,
            industry         STRING,
            generated_at     TIMESTAMP,
            content_summary  STRING,
            duration_ms      BIGINT,
            dimensions       STRING,
            codec            STRING,
            content          BINARY,
            metadata_json    STRING
        ) USING delta
        """
    else:
        sql = f"""
        CREATE OR REPLACE TABLE {fqn} (
            file_path        STRING,
            media_type       STRING,
            file_extension   STRING,
            size_bytes       BIGINT,
            industry         STRING,
            generated_at     TIMESTAMP,
            content_summary  STRING,
            duration_ms      BIGINT,
            dimensions       STRING,
            codec            STRING,
            metadata_json    STRING
        ) USING delta
        """
    execute_sql(client, warehouse_id, sql)


def _sql_str(s: str | None) -> str:
    """Single-quote escape for inline INSERT VALUES."""
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def _build_summary(type_id: str, meta: dict) -> str:
    """Per-type one-line summary for the `content_summary` column."""
    if type_id == "img_xray":
        return (
            f"X-ray {meta.get('case_id')} — {meta.get('view')}, age {meta.get('patient_age_years')}"
        )
    if type_id == "img_scan":
        return f"Scanned page: {meta.get('title')}"
    if type_id == "img_photo":
        return f"Synthetic photo {meta.get('dimensions')} — {meta.get('shape_count')} shapes"
    if type_id == "audio_voicemail":
        return f"Voicemail from {meta.get('caller_name')} to {meta.get('callee_name')}"
    if type_id == "video_clip":
        return f"MP4 clip {meta.get('dimensions')} @ {meta.get('fps')}fps for {meta.get('duration_ms')}ms"
    return type_id


def generate_media(
    client: WorkspaceClient,
    warehouse_id: str,
    config: dict,
    progress: dict | None = None,
    stop_check: Callable[[], bool] | None = None,
) -> dict:
    """Top-level orchestrator. Same contract as
    ``demo_documents.generate_documents`` so the JobManager branch
    is shape-identical.

    Per-cell failures (ffmpeg missing for video_clip, image library
    crash, etc.) are caught and recorded but do NOT abort the loop —
    other media types in the same job continue.
    """
    if not MEDIA_AVAILABLE:
        raise RuntimeError(_UNAVAILABLE_REASON or "media extra not installed")

    progress = progress if progress is not None else {}
    stopped = stop_check or (lambda: False)

    catalog = config["catalog"]
    schema = config["schema"]
    types = config.get("types") or []
    counts = config.get("counts") or {}
    industry = config.get("industry", "healthcare")
    destination = config.get("destination", "volume_with_catalog")

    if destination not in ("volume", "volume_with_catalog", "direct_table"):
        raise ValueError(f"Unknown destination: {destination!r}")
    if not types:
        raise ValueError("'types' must contain at least one media type")
    unknown = [t for t in types if t not in MEDIA_TYPES]
    if unknown:
        raise ValueError(f"Unknown media types: {unknown}. Known: {sorted(MEDIA_TYPES)}")

    from faker import Faker

    fkr = Faker(locale=config.get("faker_locale", "en_US"))
    if config.get("faker_seed") is not None:
        fkr.seed_instance(int(config["faker_seed"]))

    # AI client — opt-in via realistic_content. Reuses the shared
    # adapter that routes through Databricks Model Serving (when an
    # endpoint is picked in Settings) or the Anthropic API. Media
    # generators that produce binary bytes (images / video) ignore
    # the adapter; audio_voicemail uses it to draft a transcript when
    # available.
    from src.ai_drafter import build_drafter

    ai_client = build_drafter(config, sdk_client=client)

    volume_path: str | None = None
    table_fqn: str | None = None
    if destination in ("volume", "volume_with_catalog"):
        volume = config.get("volume") or "demo_unstructured"
        vol_fqn = f"{catalog}.{schema}.{volume}"
        _ensure_volume(client, warehouse_id, vol_fqn)
        volume_path = f"/Volumes/{catalog}/{schema}/{volume}/media"

    if destination == "volume_with_catalog":
        table_fqn = f"{catalog}.{schema}.demo_media_catalog"
        _ensure_catalog_table(client, warehouse_id, table_fqn, direct=False)
    elif destination == "direct_table":
        table_fqn = f"{catalog}.{schema}.demo_media"
        _ensure_catalog_table(client, warehouse_id, table_fqn, direct=True)

    progress.setdefault("files_written", 0)
    progress.setdefault("total_bytes", 0)
    progress.setdefault("per_type", {t: 0 for t in types})
    progress.setdefault("per_type_failures", {})
    progress.setdefault("destination", destination)

    pending_rows: list[str] = []
    BATCH_SIZE = 50

    def _flush_pending() -> None:
        nonlocal pending_rows
        if not pending_rows or table_fqn is None:
            return
        cols = (
            "file_path",
            "media_type",
            "file_extension",
            "size_bytes",
            "industry",
            "generated_at",
            "content_summary",
            "duration_ms",
            "dimensions",
            "codec",
            "metadata_json",
        )
        sql = f"INSERT INTO {table_fqn} ({', '.join(cols)}) VALUES {', '.join(pending_rows)}"
        execute_sql(client, warehouse_id, sql)
        pending_rows = []

    started_at = datetime.now(timezone.utc)

    for type_id in types:
        if stopped():
            break
        n = int(counts.get(type_id, 5))
        type_def = MEDIA_TYPES[type_id]
        gen_fn_name = type_def["gen_fn"]
        gen_fn = globals().get(gen_fn_name)
        if gen_fn is None:
            logger.error(f"Generator not found: {gen_fn_name}")
            continue

        # Per-type pre-check: video_clip needs ffmpeg. Skip the WHOLE
        # type's count when ffmpeg is missing so we don't burn time
        # generating dozens of fixtures only to fail each one
        # individually with the same error.
        if type_id == "video_clip":
            ok, reason = _ffmpeg_available()
            if not ok:
                progress["per_type_failures"][type_id] = reason or "ffmpeg missing"
                logger.warning(f"Skipping {type_id} (×{n}): {reason}")
                continue

        progress["current_type"] = type_id

        for seq in range(n):
            if stopped():
                break
            try:
                file_bytes, meta = gen_fn(industry, fkr, ai_client)
            except Exception as e:
                logger.error(f"  ✗ {type_id} #{seq}: {e}")
                # Record the first failure per-type but keep trying
                # the remaining seq — a transient ffmpeg error on one
                # frame shouldn't blank the rest of the type.
                progress["per_type_failures"].setdefault(type_id, str(e))
                continue
            file_id = uuid.uuid4().hex
            ext = type_def["extension"]
            file_name = f"{type_id}_{file_id}.{ext}"

            current_path: str | None = None
            if volume_path is not None:
                current_path = f"{volume_path}/{type_id}/{file_name}"
                client.files.upload(
                    file_path=current_path,
                    contents=io.BytesIO(file_bytes),
                    overwrite=True,
                )

            content_summary = _build_summary(type_id, meta)
            duration_ms = int(meta.get("duration_ms") or 0)
            dimensions = meta.get("dimensions") or meta.get("page_dimensions") or ""
            codec = meta.get("codec") or meta.get("format", "")
            metadata_json = json.dumps(meta, default=str)

            if destination == "volume_with_catalog" and current_path:
                row = (
                    f"({_sql_str(current_path)}, "
                    f"{_sql_str(type_id)}, "
                    f"{_sql_str(ext)}, "
                    f"{len(file_bytes)}, "
                    f"{_sql_str(industry)}, "
                    f"current_timestamp(), "
                    f"{_sql_str(content_summary)}, "
                    f"{duration_ms}, "
                    f"{_sql_str(dimensions)}, "
                    f"{_sql_str(codec)}, "
                    f"{_sql_str(metadata_json)})"
                )
                pending_rows.append(row)
            elif destination == "direct_table":
                _insert_direct_row(
                    client,
                    warehouse_id,
                    table_fqn or "",
                    file_id=file_id,
                    media_type=type_id,
                    file_extension=ext,
                    size_bytes=len(file_bytes),
                    industry=industry,
                    content_summary=content_summary,
                    duration_ms=duration_ms,
                    dimensions=dimensions,
                    codec=codec,
                    content=file_bytes,
                    metadata_json=metadata_json,
                )

            progress["files_written"] = progress.get("files_written", 0) + 1
            progress["total_bytes"] = progress.get("total_bytes", 0) + len(file_bytes)
            progress["per_type"][type_id] = progress["per_type"].get(type_id, 0) + 1
            if current_path:
                progress["current_path"] = current_path

            if destination == "volume_with_catalog" and len(pending_rows) >= BATCH_SIZE:
                _flush_pending()

    _flush_pending()

    completed_at = datetime.now(timezone.utc)
    duration_ms = int((completed_at - started_at).total_seconds() * 1000)
    from src.ai_drafter import adapter_summary

    result = {
        "status": "completed",
        "files_written": progress["files_written"],
        "total_bytes": progress["total_bytes"],
        "per_type": progress["per_type"],
        "per_type_failures": progress.get("per_type_failures", {}),
        "destination": destination,
        "volume_path": volume_path,
        "table_fqn": table_fqn,
        "duration_ms": duration_ms,
        "started_at": started_at.isoformat(timespec="seconds"),
        "completed_at": completed_at.isoformat(timespec="seconds"),
    }
    result.update(adapter_summary(ai_client))
    return result


def _insert_direct_row(
    client: WorkspaceClient,
    warehouse_id: str,
    table_fqn: str,
    *,
    file_id: str,
    media_type: str,
    file_extension: str,
    size_bytes: int,
    industry: str,
    content_summary: str,
    duration_ms: int,
    dimensions: str,
    codec: str,
    content: bytes,
    metadata_json: str,
) -> None:
    """Insert one row into the direct table with the binary `content`.

    Uses unhex(hex(...)) for portable BINARY embedding (same approach
    `demo_documents._insert_direct_row` uses). Per-row INSERT is
    slower than batched but correct — bulk binary INSERT batching is
    a v2 optimisation across both modules.
    """
    hex_content = content.hex()
    sql = (
        f"INSERT INTO {table_fqn} "
        f"(file_id, media_type, file_extension, size_bytes, industry, "
        f"generated_at, content_summary, duration_ms, dimensions, codec, "
        f"content, metadata_json) "
        f"VALUES ("
        f"{_sql_str(file_id)}, "
        f"{_sql_str(media_type)}, "
        f"{_sql_str(file_extension)}, "
        f"{size_bytes}, "
        f"{_sql_str(industry)}, "
        f"current_timestamp(), "
        f"{_sql_str(content_summary)}, "
        f"{duration_ms}, "
        f"{_sql_str(dimensions)}, "
        f"{_sql_str(codec)}, "
        f"unhex('{hex_content}'), "
        f"{_sql_str(metadata_json)})"
    )
    execute_sql(client, warehouse_id, sql)


# ── Preview (pure arithmetic) ─────────────────────────────────────


def preview_media(config: dict) -> dict:
    """Return per-type / total estimates without going near the
    warehouse. Mirrors ``demo_documents.preview_documents``.
    """
    types = config.get("types") or []
    counts = config.get("counts") or {}
    per_type = []
    total_files = 0
    total_bytes = 0
    total_seconds = 0.0
    unknown: list[str] = []
    for t in types:
        if t not in MEDIA_TYPES:
            unknown.append(t)
            continue
        n = int(counts.get(t, 5))
        bytes_each = _AVG_BYTES_PER_TYPE.get(t, 50_000)
        per_sec = _GEN_PER_SECOND_PER_TYPE.get(t, 100)
        per_type.append(
            {
                "type": t,
                "category": MEDIA_TYPES[t]["category"],
                "label": MEDIA_TYPES[t]["label"],
                "count": n,
                "estimated_bytes": n * bytes_each,
                "estimated_seconds": round(n / per_sec, 1),
            }
        )
        total_files += n
        total_bytes += n * bytes_each
        total_seconds += n / per_sec
    return {
        "per_type": per_type,
        "total_files": total_files,
        "total_bytes": total_bytes,
        "estimated_seconds": round(total_seconds, 1),
        "unknown_types": unknown,
    }
