"""Cross-format type / feature compatibility checks (D2 of #9 N×N converter).

The convert path runs these *before* any DDL — refusing a conversion
at planning time is much friendlier than letting the warehouse fail
midway through a CTAS with a cryptic type-mismatch error. Each check
returns either ``None`` (compatible) or a short reason string the API
surfaces inside the 422 body.

Why declarative: the matrix has 16 cells (4 formats × 4 targets) and
will gain more checks as edge cases surface. A `dict[(src, tgt)] →
list[Check]` makes it cheap to add a new pair-specific check without
threading more `if/elif` into the orchestrator. Same compat layer
runs at dry-run time *and* execution time, so the preview matches
reality.

What's checked here today:

- ``(ICEBERG, *)`` re-uses the existing
  ``clone_iceberg.preflight_iceberg_source`` to refuse hidden
  partitioning. Hidden partition transforms (`bucket(N, col)`,
  `truncate`, `years`, `months`, `days`, `hours`) have no Delta /
  Parquet equivalent; silently dropping them changes partition-pruning
  semantics, which we won't do.
- ``(DELTA, ICEBERG)`` and ``(DELTA, PARQUET)`` refuse generated and
  identity columns. Iceberg has no equivalent of Delta's GENERATED
  ALWAYS AS / IDENTITY; round-tripping is lossy and silent loss
  becomes an incident a week later. Parquet has neither concept.

What's intentionally *not* checked yet (deferred to D3 or later):
type-level losses like ``TIMESTAMP_NTZ → INT96`` or column comments
that don't survive Parquet. Those degrade silently rather than break
data correctness; surface them as warnings in a follow-up rather than
failing a clone today.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass

from databricks.sdk import WorkspaceClient

from src.client import execute_sql

logger = logging.getLogger(__name__)


@dataclass
class CompatCheckResult:
    """Result of one compat check. ``reason`` is None on pass, a short
    operator-readable string on fail. The orchestrator joins all
    failures into one 422 body so the user sees every problem in a
    single response, not one round-trip per check."""

    reason: str | None = None

    @property
    def ok(self) -> bool:
        return self.reason is None


# A check signature: (client, warehouse_id, fqn) → CompatCheckResult.
# Registered per-(source_format, target_format) pair below.
CompatCheck = Callable[[WorkspaceClient, str, str], CompatCheckResult]


def _refuse_hidden_iceberg_partitions(
    client: WorkspaceClient, warehouse_id: str, fqn: str
) -> CompatCheckResult:
    """Reuse the existing Iceberg preflight from clone_iceberg.

    Imported lazily to avoid the circular dependency (clone_iceberg
    imports from src.client; format_compat is consumed by
    convert_to_delta which doesn't depend on clone_iceberg directly).
    """
    from src.clone_iceberg import IcebergPreflightError, preflight_iceberg_source

    try:
        preflight_iceberg_source(client, warehouse_id, fqn)
    except IcebergPreflightError as pe:
        return CompatCheckResult(reason=str(pe))
    return CompatCheckResult()


def _refuse_delta_generated_or_identity_columns(
    client: WorkspaceClient, warehouse_id: str, fqn: str
) -> CompatCheckResult:
    """Refuse Delta sources whose schema has GENERATED / IDENTITY
    columns when the target format has no equivalent.

    Detects via ``DESCRIBE TABLE EXTENDED`` — looks for `generated
    always` or `generated by default` in the data_type column or
    comment field. Fails open (returns ok) if the DESCRIBE fails so a
    flaky warehouse doesn't block the conversion.
    """
    try:
        rows = execute_sql(client, warehouse_id, f"DESCRIBE TABLE EXTENDED {fqn}")
    except Exception as e:
        logger.debug("compat DESCRIBE failed on %s, assuming OK: %s", fqn, e)
        return CompatCheckResult()

    for row in rows:
        col = (row.get("col_name") or "").strip()
        if col.startswith("#") or not col:
            continue
        # The combined view: column "data_type" sometimes contains the
        # full column definition with GENERATED/IDENTITY clauses on
        # newer DBR; "comment" sometimes carries it on older DBR. Check
        # both rather than guess the runtime version.
        data_type = (row.get("data_type") or "").lower()
        comment = (row.get("comment") or "").lower()
        if "generated always" in data_type or "generated by default" in data_type:
            return CompatCheckResult(
                reason=(
                    f"column '{col}' is GENERATED — the target format has no "
                    f"equivalent. Drop the column or change the target."
                )
            )
        if "identity column" in comment or "is_identity" in data_type:
            return CompatCheckResult(
                reason=(
                    f"column '{col}' is an IDENTITY column — the target format "
                    f"has no equivalent. Drop the column or change the target."
                )
            )
    return CompatCheckResult()


def _refuse_hudi_uniform_when_iceberg_active(
    client: WorkspaceClient, warehouse_id: str, fqn: str
) -> CompatCheckResult:
    """Refuse Delta→Hudi UniForm when the table is already an Iceberg
    UniForm sidecar (or a UC Managed Iceberg table).

    UniForm sidecars are **mutually exclusive** on a single Delta
    table — Databricks rejects ``ALTER TABLE ... SET TBLPROPERTIES
    ('delta.universalFormat.enabledFormats' = 'hudi')`` with
    ``MANAGED_ICEBERG_OPERATION_NOT_SUPPORTED`` when Iceberg is
    already enabled. The error isn't documented; we surface it
    up-front instead of letting the operator hit the cryptic
    Databricks error after a 4-second SQL round-trip.

    Detects via ``SHOW TBLPROPERTIES`` — checks two flags:
      - ``delta.enableIcebergCompatV2`` (Iceberg UniForm enabled)
      - ``delta.universalFormat.enabledFormats`` containing ``iceberg``

    Fails open (returns ok) if SHOW TBLPROPERTIES errors so a flaky
    warehouse doesn't block the conversion.
    """
    try:
        rows = execute_sql(client, warehouse_id, f"SHOW TBLPROPERTIES {fqn}")
    except Exception as e:
        logger.debug(
            "Hudi UniForm preflight SHOW TBLPROPERTIES failed on %s, assuming OK: %s", fqn, e
        )
        return CompatCheckResult()

    iceberg_compat_on = False
    enabled_formats = ""
    for row in rows or []:
        # SHOW TBLPROPERTIES returns columns named differently across
        # DBR versions: "key"/"value" on newer, "Key"/"Value" elsewhere.
        # Normalise both shapes.
        key = (row.get("key") or row.get("Key") or "").strip().lower()
        val = (row.get("value") or row.get("Value") or "").strip().lower()
        if key == "delta.enableicebergcompatv2" and val == "true":
            iceberg_compat_on = True
        if key == "delta.universalformat.enabledformats":
            enabled_formats = val

    iceberg_already_active = iceberg_compat_on or "iceberg" in enabled_formats
    if iceberg_already_active:
        return CompatCheckResult(
            reason=(
                "Hudi UniForm cannot be enabled — Iceberg UniForm is already "
                "active on this table (UniForm sidecars are mutually exclusive). "
                "To switch to Hudi, first run: "
                "ALTER TABLE <fqn> UNSET TBLPROPERTIES "
                "('delta.enableIcebergCompatV2', 'delta.universalFormat.enabledFormats')"
            )
        )
    return CompatCheckResult()


# Per-pair check registry. Order doesn't matter; the orchestrator runs
# every check and joins failures. New pairs in future phases register
# here; downstream consumers don't change.
_COMPAT_CHECKS: dict[tuple[str, str], list[CompatCheck]] = {
    # Hidden-partitioning refusal applies whenever the SOURCE is
    # Iceberg, regardless of target. Same physical incompatibility:
    # Delta and Parquet have no `bucket(N, col)` equivalent.
    ("ICEBERG", "DELTA"): [_refuse_hidden_iceberg_partitions],
    ("ICEBERG", "PARQUET"): [_refuse_hidden_iceberg_partitions],
    # GENERATED / IDENTITY columns on Delta sources don't survive a
    # CTAS into Iceberg or Parquet. UniForm-update path keeps the
    # table as Delta, so it's fine — no check registered for that
    # logical pair (the UniForm strategy handles columns transparently).
    ("DELTA", "ICEBERG"): [_refuse_delta_generated_or_identity_columns],
    ("DELTA", "PARQUET"): [_refuse_delta_generated_or_identity_columns],
    # Delta→Hudi UniForm refuses if Iceberg UniForm is already enabled
    # (Databricks rejects setting both sidecars on one table). See
    # `_refuse_hudi_uniform_when_iceberg_active` for the exact rule.
    ("DELTA", "HUDI"): [_refuse_hudi_uniform_when_iceberg_active],
}


def check_pair_compat(
    client: WorkspaceClient,
    warehouse_id: str,
    fqn: str,
    source_format: str,
    target_format: str,
) -> list[str]:
    """Run every registered check for the (source, target) pair.

    Returns a list of operator-readable reasons. Empty list means
    compatible — proceed with the conversion. The convert orchestrator
    treats a non-empty list as a refusal and surfaces it as a 422 (via
    the API) or a ``ConvertResult(status="skipped", error=...)`` (via
    the per-table function).

    For pairs with no registered checks (e.g. Parquet→Delta), returns
    an empty list immediately. This mirrors the design of
    ``SUPPORTED_PAIRS`` — the orchestrator and the API model both
    agree on what's "no checks needed" without coordination.
    """
    src = source_format.upper()
    tgt = target_format.upper()
    checks = _COMPAT_CHECKS.get((src, tgt), [])
    reasons: list[str] = []
    for check in checks:
        result = check(client, warehouse_id, fqn)
        if not result.ok and result.reason is not None:
            reasons.append(result.reason)
    return reasons
